<a href="https://colab.research.google.com/github/santiagorg2401/ras_choreographies/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0. PyTorch Fundamentals


In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


## 1. Tensors
Tensors are a form of data representation.

### Scalars, vectors, matrices and tensors
* For nomenclature, matrices and Tensors are typed in uppercase whereas vectors in lowecase.

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar, scalar.ndim, scalar.item()

(tensor(7), 0, 7)

In [3]:
# Vector
vector = torch.tensor([7, 7])
vector, vector.ndim, vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [4]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 9]])
MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[7, 8],
         [9, 9]]),
 2,
 torch.Size([2, 2]))

In [5]:
# Tensor
TENSOR = torch.tensor([[[1, 2],
                        [3, 4],
                        [5, 6]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[1, 2],
          [3, 4],
          [5, 6]]]),
 3,
 torch.Size([1, 3, 2]))

### Random tensors

In [6]:
# Random tensor
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.9440, 0.4947, 0.4366, 0.7148],
         [0.6651, 0.1917, 0.1155, 0.2216],
         [0.6853, 0.4766, 0.2882, 0.7570]]),
 2,
 torch.Size([3, 4]))

In [7]:
# Random tensor with similar shape to an image tensor.
random_image = torch.rand((224, 224, 3))
random_image[:2], random_image.ndim, random_image.shape

(tensor([[[4.3716e-01, 6.9632e-01, 8.4808e-01],
          [2.0639e-01, 2.2194e-01, 7.0791e-01],
          [2.1622e-01, 8.2207e-04, 6.0048e-01],
          ...,
          [8.8643e-01, 8.2345e-01, 2.5463e-01],
          [3.6090e-01, 6.5855e-01, 4.7082e-01],
          [5.3820e-01, 6.7138e-01, 9.4068e-01]],
 
         [[7.6728e-01, 9.7625e-01, 2.9693e-01],
          [2.3855e-01, 6.7107e-01, 2.1200e-01],
          [8.1651e-01, 5.3214e-01, 9.0821e-01],
          ...,
          [1.2709e-01, 9.8254e-01, 9.7316e-01],
          [7.3888e-01, 3.1553e-01, 3.1092e-02],
          [8.7403e-01, 1.3174e-01, 5.4789e-01]]]),
 3,
 torch.Size([224, 224, 3]))

### Zeros and ones

In [8]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
ones = torch.ones((3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

### Range of tensors and tensors-like

In [11]:
range = torch.arange(0, 10)
range, range.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [12]:
range2 = torch.arange(start=0, end=100, step=20)
range2

tensor([ 0, 20, 40, 60, 80])

In [13]:
tensor_like = torch.zeros_like(range)
tensor_like, tensor_like.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([10]))

## 2. Getting information from tensors.
Most common errors are about type, shape and device.

### Tensor datatypes
The default datatype in PyTorch is float32. Generally, operations between tensors with different types will error.

In [14]:
tensor = torch.tensor([3.0, 6.0, 9.0],
                      dtype=None,
                      device=None,
                      requires_grad=False)
tensor, tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [15]:
tensor2 = tensor.type(torch.float16)
tensor2

tensor([3., 6., 9.], dtype=torch.float16)

In [16]:
tensor3 = tensor * tensor2
tensor3, tensor3.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [17]:
torch.tensor([1,2,3], dtype=torch.int32) * tensor

tensor([ 3., 12., 27.])

### Tensor shape

In [18]:
tensor.shape, tensor.size()

(torch.Size([3]), torch.Size([3]))

### Tensor device
By default, tensors are stored in CPU

In [19]:
tensor.device

device(type='cpu')

## 3. Tensor operations
* Addtion
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [20]:
# Addition
X = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
X + 10, torch.add(X, 10)

(tensor([[11, 12, 13],
         [14, 15, 16]]),
 tensor([[11, 12, 13],
         [14, 15, 16]]))

In [21]:
# Subtraction
X - 10, torch.sub(X, 10)

(tensor([[-9, -8, -7],
         [-6, -5, -4]]),
 tensor([[-9, -8, -7],
         [-6, -5, -4]]))

In [22]:
# Multiplication
X * 10, torch.mul(X, 10)

(tensor([[10, 20, 30],
         [40, 50, 60]]),
 tensor([[10, 20, 30],
         [40, 50, 60]]))

In [23]:
# Division
X / 10, torch.div(X, 10)

(tensor([[0.1000, 0.2000, 0.3000],
         [0.4000, 0.5000, 0.6000]]),
 tensor([[0.1000, 0.2000, 0.3000],
         [0.4000, 0.5000, 0.6000]]))

In [24]:
# Matrix multiplication (element-wise)
y = torch.tensor([[7, 8 ,9],
                  [10, 11, 12]])
X * y, torch.mul(X, y)

(tensor([[ 7, 16, 27],
         [40, 55, 72]]),
 tensor([[ 7, 16, 27],
         [40, 55, 72]]))

In [25]:
# Matrix multiplication
X @ torch.transpose(y, 0, 1), torch.matmul(X, torch.transpose(y, 0, 1))

(tensor([[ 50,  68],
         [122, 167]]),
 tensor([[ 50,  68],
         [122, 167]]))

## 4. Common errors

In [26]:
# Inner dimensions must match
try:
  torch.matmul(torch.rand(3, 2), torch.rand(3, 2))
except Exception as e:
  print(e)

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


## 5. Tensor aggregation

In [27]:
x = torch.arange(0, 100, 10)

In [28]:
# min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [29]:
# max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [30]:
# mean. mean requires float32 datatype.
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [31]:
# sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [32]:
# argmin (positional min)
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [33]:
# argmax (positional max)
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## 6. Reshaping, stacking, squeezing and unsqueezing

In [34]:
x  = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [35]:
# Reshaping
try:
  y = x.reshape(1, 7)
except Exception as e:
  print(e)

y = x.reshape(1, 9)
y, y.shape

shape '[1, 7]' is invalid for input of size 9


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [37]:
# Changing z changes x as it shares memory
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [38]:
# Stack
z = torch.stack([x, x, x, x])
w = torch.stack([x, x, x, x], dim=1)
z, w

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]))

In [39]:
# Squeeze
x = torch.zeros(1, 2, 3)
y = torch.squeeze(x)
x, x.shape, y, y.shape

(tensor([[[0., 0., 0.],
          [0., 0., 0.]]]),
 torch.Size([1, 2, 3]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([2, 3]))

In [40]:
# Unsqueeze
y = torch.unsqueeze(y, dim=0)
y, y.shape

(tensor([[[0., 0., 0.],
          [0., 0., 0.]]]),
 torch.Size([1, 2, 3]))

In [41]:
# Permute - "reorder". A permute is also a view, then it shares the same space of memory
y = torch.permute(x, (2, 1, 0))
x, x.shape, y, y.shape

(tensor([[[0., 0., 0.],
          [0., 0., 0.]]]),
 torch.Size([1, 2, 3]),
 tensor([[[0.],
          [0.]],
 
         [[0.],
          [0.]],
 
         [[0.],
          [0.]]]),
 torch.Size([3, 2, 1]))

## 7. Indexing

In [42]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [43]:
# Index 0th dimension
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
# Index 1st dimension
x[0, 0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [45]:
# Index 2nd dimension
x[0, 0, 0], x[0][0][0]

(tensor(1), tensor(1))

In [46]:
# : selects all elements of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [47]:
# Get all values from 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [48]:
# Get all values from 0th but only 1 from 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [49]:
# Get index 0 from 0th and 1st dimension and all values from 2nd
x[0, 0, :]

tensor([1, 2, 3])

## 8. PyTorch and NumPy

In [50]:
import numpy as np

# Numpy to tensor. When converting np to torch it conserves the original data type
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor, array.dtype, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'),
 torch.float64)

In [51]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, tensor.dtype, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 torch.float32,
 dtype('float32'))

## 9. Reproducibility

In [52]:
# Random states does not allow for reproducibility as every iteration is different
x = torch.rand(3, 4)
y = torch.rand(3, 4)

x, y, x == y

(tensor([[0.6199, 0.0263, 0.6796, 0.1652],
         [0.2348, 0.8342, 0.6652, 0.1693],
         [0.0502, 0.9618, 0.6079, 0.3971]]),
 tensor([[0.3713, 0.8750, 0.9700, 0.1899],
         [0.1864, 0.9221, 0.8250, 0.7473],
         [0.4747, 0.8641, 0.5863, 0.4717]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [53]:
# Set a random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

x = torch.rand(3, 4)
y = torch.rand(3, 4)
x, y, x == y

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [54]:
# Set a random seed. Manual seed only works per code block
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

x = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
y = torch.rand(3, 4)
x, y, x == y

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

## 10. Running Tensor on GPU

In [55]:
!nvidia-smi

Mon Aug 28 15:12:07 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [56]:
# Check for GPU access
torch.cuda.is_available()

True

In [57]:
# Setup device agnostig code (CUDA best practices with PyTorch)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [58]:
# Count number of devices
torch.cuda.device_count()

1

In [59]:
# Tensor not on GPU
x = torch.tensor([1, 2, 3])
x, x.device

(tensor([1, 2, 3]), device(type='cpu'))

In [60]:
# Move tensor to GPU if available
y = x.to(device)
y, y.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [61]:
# Try to convert GPU tensor in Numpy
try:
  y.numpy()
except Exception as e:
  print(e)

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [62]:
# Return tensor to CPU
z = y.cpu()
w = z.numpy()
z, z.device, w

(tensor([1, 2, 3]), device(type='cpu'), array([1, 2, 3]))